insert  into students (sid, sname, major, s_level, age)
     values (1, 'james joyce', 'humanities', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (2, 'georges bataille', 'library science', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (3, 'pablo picasso', 'biology', 'senior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (4, 'martin heidegger', 'physics', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (5, 'friedrich schelling', 'physics', 'senior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (6, 'edmund husserl', 'mathematics', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (7, 'john dewey', 'humanities', 'sophomore', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (8, 'max scheler', 'psychology', 'sophomore', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (9, 'gilles deleuze', 'mathematics', 'freshman', 17)
/insert  into students (sid, sname, major, s_level, age)
     values (10, 'thomas pynchon', 'engineering', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (11, 'nick cave', 'music', 'junior', 21)
/insert  into department (did, dname)
     values (999, 'ADMIN')
/insert  into department (did, dname)
     values (101, 'humanities')
/insert  into department (did, dname)
     values (102, 'mathematics')
/insert  into department (did, dname)
     values (103, 'english')
/insert  into department (did, dname)
     values (104, 'history')
/insert  into department (did, dname)
     values (105, 'psychology')
/insert  into department (did, dname)
     values (106, 'theater')
/insert  into department (did, dname)
     values (107, 'physics')
/insert  into department (did, dname)
     values (108, 'engineering')
/insert  into department (did, dname)
     values (109, 'music')
/insert  into department (did, dname)
     values (110, 'basket weaving')
/insert  into faculty (fid, fname, deptid)
     values (1, 'slavoj zizek', 101)
/insert  into faculty (fid, fname, deptid)
     values (2, 'soren kierkegaard', 102)
/insert  into faculty (fid, fname, deptid)
     values (3, 'richard stallman', 103)
/insert  into faculty (fid, fname, deptid)
     values (4, 'charles peirce', 104)
/insert  into faculty (fid, fname, deptid)
     values (5, 'gottfried hegel', 105)
/insert  into faculty (fid, fname, deptid)
     values (6, 'hannah arendt', 106)
/insert  into faculty (fid, fname, deptid)
     values (7, 'ingmar bergman', 107)
/insert  into faculty (fid, fname, deptid)
     values (8, 'lary wall', 108)
/insert  into faculty (fid, fname, deptid)
     values (9, 'marlon brando', 109)
/insert  into faculty (fid, fname, deptid)
     values (10, 'friedrich nietzsche', 110)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('HUM101', 'intro to humanity', 'MWF 10:00-10:50', 'ALPHA 0001', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('MATH220', 'numbers big and small', 'Tu 1:00-3:50', 'BETA 0020', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('PHYS439', 'advanced time travel', 'WF 4:00-4:30', 'GAMMA 0333', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('MUS330', 'special topic: pierrot lunaire', 'MWF 12:00-12:50', 'DELTA 4040', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('BASK101', 'intro to baskets', 'TuTh 5:00-6:30', 'EPSILON 0055', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('HIST412', 'roman economy', 'MWF 9:00-9:50', 'ZETA 0606', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('ENGIN120', 'augers and levers', 'W 9:00-11:30', 'ETA 7007', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('ENGLISH450', 'race, gender, class in pre-soviet anglophone lit', 'TuTh 4:00-4:50', 'THETA 0888', null, 50)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('THEAT230', 'advanced staged death scenes', 'MWF 8:00-8:50', 'IOTA 0909', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit
     values ('PSYCH401', 'mind-melding', 'Tu 3:00-5:30', 'KAPPA 0101', null, 10)
/insert  into staff (sid, sname, deptid)
     values (1, 'richard james', 101)
/insert  into staff (sid, sname, deptid)
     values (2, 'jack nicholls', 102)
/insert  into staff (sid, sname, deptid)
     values (3, 'staffbot gamma', 103)
/insert  into staff (sid, sname, deptid)
     values (4, 'cornelius cambermain', 104)
/insert  into staff (sid, sname, deptid)
     values (5, 'edwin stencil', 105)
/insert  into staff (sid, sname, deptid)
     values (6, 'benny profane', 106)
/insert  into staff (sid, sname, deptid)
     values (7, 'billy pilgrim', 107)
/insert  into staff (sid, sname, deptid)
     values (8, 'billy corgan', 108)
/insert  into staff (sid, sname, deptid)
     values (9, 'tyrone slothrop', 109)
/insert  into staff (sid, sname, deptid)
     values (10, 'humbert humbert', 110)
/insert  into staff (sid, sname, deptid)
     values (11, 'the dean', 999)
/