insert  into students (sid, sname, major, s_level, age)
     values (1, 'james joyce', 'humanities', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (2, 'georges bataille', 'library science', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (3, 'pablo picasso', 'biology', 'senior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (4, 'martin heidegger', 'physics', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (5, 'friedrich schelling', 'physics', 'senior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (6, 'edmund husserl', 'mathematics', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (7, 'john dewey', 'humanities', 'sophomore', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (8, 'max scheler', 'psychology', 'sophomore', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (9, 'gilles deleuze', 'mathematics', 'freshman', 17)
/insert  into students (sid, sname, major, s_level, age)
     values (10, 'thomas pynchon', 'engineering', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (11, 'nick cave', 'music', 'junior', 21)
/insert  into students (sid, sname, major, s_level, age)
     values (12, 'gregor samsa', 'literature', 'sophomore', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (13, 'jim webb', 'racquet sports', 'freshman', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (14, 'gordon freeman', 'physics', 'senior', 22)
/insert  into students (sid, sname, major, s_level, age)
     values (15, 'flannery oconnor', 'chemistry', 'junior', 22)
/insert  into students (sid, sname, major, s_level, age)
     values (16, 'ada lovelace', 'psychology', 'freshman', 21)
/insert  into students (sid, sname, major, s_level, age)
     values (17, 'jean baudrillard', 'mathematics', 'senior', 23)
/insert  into students (sid, sname, major, s_level, age)
     values (18, 'yukio mishima', 'fencing', 'senior', 23)
/insert  into students (sid, sname, major, s_level, age)
     values (19, 'stephen malkmus', 'poetry', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (20, 'john connor', 'engineering', 'sophomore', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (21, 'diogenes laertius', 'speech-comm', 'senior', 21)
/insert  into students (sid, sname, major, s_level, age)
     values (22, 'judith butler', 'racquet sports', 'freshman', 18)
/insert  into students (sid, sname, major, s_level, age)
     values (23, 'susan sontag', 'information technology', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (24, 'franz ferdinand', 'poli-sci', 'junior', 20)
/insert  into students (sid, sname, major, s_level, age)
     values (25, 'john cage', 'mathematics', 'freshman', 19)
/insert  into students (sid, sname, major, s_level, age)
     values (26, 'joseph beuys', 'art history', 'junior', 20)
/insert  into department (did, dname)
     values (999, 'ADMIN')
/insert  into department (did, dname)
     values (101, 'humanities')
/insert  into department (did, dname)
     values (102, 'sciences')
/insert  into department (did, dname)
     values (103, 'english')
/insert  into department (did, dname)
     values (104, 'history')
/insert  into department (did, dname)
     values (105, 'psychology')
/insert  into faculty (fid, fname, deptid)
     values (1, 'slavoj zizek', 101)
/insert  into faculty (fid, fname, deptid)
     values (2, 'soren kierkegaard', 102)
/insert  into faculty (fid, fname, deptid)
     values (3, 'richard stallman', 103)
/insert  into faculty (fid, fname, deptid)
     values (4, 'charles peirce', 104)
/insert  into faculty (fid, fname, deptid)
     values (5, 'gottfried hegel', 105)
/insert  into faculty (fid, fname, deptid)
     values (6, 'hannah arendt', 101)
/insert  into faculty (fid, fname, deptid)
     values (7, 'ingmar bergman', 102)
/insert  into faculty (fid, fname, deptid)
     values (8, 'lary wall', 103)
/insert  into faculty (fid, fname, deptid)
     values (9, 'marlon brando', 104)
/insert  into faculty (fid, fname, deptid)
     values (10, 'friedrich nietzsche', 105)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('HUM101', 'intro to humanity', 'MWF 10:00-10:50', 'ALPHA 0001', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('MATH220', 'numbers big and small', 'Tu 1:00-3:50', 'BETA 0020', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('PHYS439', 'advanced time travel', 'WF 16:00-16:30', 'GAMMA 0333', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('MUS330', 'special topic: pierrot lunaire', 'MWF 12:00-12:50', 'DELTA 4040', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('BASK101', 'intro to baskets', 'TuTh 17:00-18:30', 'EPSILON 0055', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('HIST412', 'roman economy', 'MWF 9:00-9:50', 'ZETA 0606', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('ENGIN120', 'augers and levers', 'W 9:00-11:30', 'ETA 7007', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('ENGLISH450', 'race, gender, class in pre-soviet anglophone lit', 'TuTh 16:00-16:50', 'THETA 0888', null, 50)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('THEAT230', 'advanced staged death scenes', 'MWF 8:00-8:50', 'IOTA 0909', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('PSYCH401', 'mind-melding', 'Tu 15:00-17:30', 'KAPPA 0101', null, 10)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('HUM201', 'advanced humanity, 'MWF 11:00-11:50', 'ALPHA 0001', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('MATH320', 'concrete mathematics', 'Tu 10:00-10:50', 'BETA 0022', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('PHYS239', 'intro to matter', 'WF 16:00-16:30', 'GAMMA 0338', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('MUS130', 'special topic: harmonic minor scales', 'F 17:00-17:50', 'DELTA 4040', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('BASK201', 'advanced weaving', 'TuTh 17:00-18:30', 'EPSILON 0055', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('HIST312', 'coins', 'Tu 7:00-7:50', 'ZETA 0606', null, 20)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('ENGIN420', 'pulleys', 'W 18:00-19:30', 'ETA 7007', null, 30)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('ENGLISH455', 'race, gender, class in post-soviet anglophone lit', 'TuTh 17:00-17:50', 'THETA 0888', null, 50)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('THEAT130', 'fake laughter', 'MWF 20:00-20:50', 'IOTA 0909', null, 15)
/insert  into courses (cid, cname, meets_at, room, fid, limit)
     values ('PSYCH402', 'mind-unmelding', 'Tu 18:00-18:30', 'KAPPA 0101', null, 10)
/insert  into staff (sid, sname, deptid)
     values (1, 'richard james', 101)
/insert  into staff (sid, sname, deptid)
     values (2, 'jack nicholls', 102)
/insert  into staff (sid, sname, deptid)
     values (3, 'staffbot gamma', 103)
/insert  into staff (sid, sname, deptid)
     values (4, 'cornelius cambermain', 104)
/insert  into staff (sid, sname, deptid)
     values (5, 'edwin stencil', 105)
/insert  into staff (sid, sname, deptid)
     values (6, 'benny profane', 101)
/insert  into staff (sid, sname, deptid)
     values (7, 'billy pilgrim', 102)
/insert  into staff (sid, sname, deptid)
     values (8, 'billy corgan', 103)
/insert  into staff (sid, sname, deptid)
     values (9, 'tyrone slothrop', 104)
/insert  into staff (sid, sname, deptid)
     values (10, 'humbert humbert', 105)
/insert  into staff (sid, sname, deptid)
     values (11, 'the dean', 999)
/